#!/bin/bash


print_usage () {
    echo "Usage: ${G_PROGNAME} <option> arg";
    echo "    arg: arg description";
    return 0;
}


# main () {
    G_DEBUG_MODE='OFF';
    readonly G_PROGNAME=`basename $0`;
    
    while getopts dh opts; do
        case ${opts} in
            d) readonly G_DEBUG_MODE='ON';
               ;;
            h) print_usage;
               exit 0;;
            *) print_usage;
               exit 0;;
        esac
    done
    shift `expr ${OPTIND} - 1`

    readonly G_DEBUG_MODE;

    if [ $# -ne 1 ]; then
        print_usage;
        exit 1;
    fi

    exit 0;
# } main ()
