#!/bin/bash
# Script I wrote to generate math questions for Luc

QF=./question_file
AF=./answer_file

CURRENT_NUMBER=$(((RANDOM % 9) + 1))
CURRENT_RESULT=$((0 + CURRENT_NUMBER))
CURRENT_STR=$CURRENT_NUMBER

i=0
while [ $i -lt 1 ]; do
  OPERATION='x'

  NEW_NUMBER=$(((RANDOM % 9) + 1))
  CURRENT_NUMBER=${NEW_NUMBER}

  NEW_RESULT=$((${CURRENT_RESULT} * ${NEW_NUMBER}))
  CURRENT_STR="$CURRENT_STR $OPERATION $CURRENT_NUMBER"
  CURRENT_RESULT=$NEW_RESULT

  i=`expr $i + 1`
done

echo ${CURRENT_STR} = >> $QF
echo ${CURRENT_STR} = ${CURRENT_RESULT} >> $AF

exit 0
