#!/bin/sh
###############################################################
# get_zp_content_from_url
#
# This script parses the url from Zero Punctuation website
# then downloads the mp4 file.
#
# http://www.escapistmagazine.com/videos/view/zero-punctuation
#
###############################################################

URL=${1}
PROG_NAME=`basename $0`

if [ -z "${URL}" ]; then
	echo "Usage ${PROG_NAME} <ZP HTTP URL>"
	exit 1
fi

# Download the html file for parsing.
TMP_DIR=/tmp
HTML_FILE_NAME=`echo ${URL} | sed -re 's/.+\///'`
OUTPUT_HTML_FILE=${TMP_DIR}/${HTML_FILE_NAME}
wget -q $URL -O ${OUTPUT_HTML_FILE}

# The HTML file downloaded contains a java script file which
# contains the config for the flash media player.
JS_URL=`cat ${OUTPUT_HTML_FILE} | grep ".js" | grep config | sed -re s/^.+config=// | sed -re 's/(.+)js.+/\1/'`
JS_URL=${JS_URL}js
rm ${OUTPUT_HTML_FILE}

# Download the javascript file for parsing.
JS_FILE=`echo ${JS_URL} | sed -re 's/.+\///'`
OUTPUT_JS_FILE=${TMP_DIR}/${JS_FILE}
wget -q ${JS_URL} -O ${OUTPUT_JS_FILE}

# I suck at regexp, so I'm just going to go through the file
# until I find the correct mp4 URI.
CAN_EXIT=0;
i=0;
while [ ${CAN_EXIT} -eq 0 ]; do
	i=`expr ${i} + 1`;
	OUTPUT=`cat ${OUTPUT_JS_FILE} | cut -d \{ -f ${i} | grep mp4 | grep -v house-ad-rotation`;
	if [ -n "${OUTPUT}" ]; then
		CONTENT_URL=`echo ${OUTPUT} | sed -re 's/(.+)mp4.+/\1/' | sed -re "s/^.+url':'//"`
		CAN_EXIT=1
	fi
done

CONTENT_URL=${CONTENT_URL}mp4
rm ${OUTPUT_JS_FILE}

# Download the mp4 file and save it in a sortable file name.
wget ${CONTENT_URL} -O zp_${HTML_FILE_NAME}.mp4
