#!/bin/bash

git fetch

if [ $? -ne 0 ]; then
  echo "ERROR: Unable to git fetch".
  exit 1;
fi

git remote prune origin

if [ $? -ne 0 ]; then
  echo "ERROR: Unable to prune remote".
  exit 1;
fi

readonly LOCAL_BRANCHES=`git branch | cut -c 3-`;

for i in ${LOCAL_BRANCHES}; do
  ANSWER=''
  REMOTE_CHECK=`git branch -r | sed -e s^.*origin/g | grep -v HEAD | grep "^${i}$"`;
  if [ -z "${REMOTE_CHECK}" ]; then
    echo "Branch: ${i} is not available remote, remove locally? (Y/N)";
    read ANSWER;
    if [ "${ANSWER}" = 'y' -o "${ANSWER}" = 'Y' ]; then
      git branch -D ${i};
    fi
  fi
done

exit 0;
