#!/usr/bin/env python3

"""
 Description of script
"""

import sys
import argparse


def main(arguments):

    parser = argparse.ArgumentParser(
            description=__doc__,
            formatter_class=argparse.ArgumentDefaultsHelpFormatter
            )
    parser.add_argument(
            'm_arg', type=str, nargs=1,
            help='mandatory argument'
            )
    parser.add_argument(
            '-o', '--option', type=str,
            help='optional argument'
            )
    args = parser.parse_args(arguments)
    return 0


if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
