#!/bin/bash
#####################################################################
#
# This script is to maximize my rdesktop window, it's only setup for
# the default ubuntu 10.04 desktop settings. Because my setup is 2
# screens with one smaller than the other, I can't have the rdesktop
# connection across both of them. So I pick the largest screen and
# use that value.
#
#####################################################################


RDP_SERVER=${1}
PROG_NAME=`basename $0`

if [ -z ${RDP_SERVER} ]; then
	echo "Usage: ${PROG_NAME} <rdp server name or ip>"
	exit 1
fi

CONF_HEIGHT=0
for i in `cat ~/.config/monitors.xml  | grep height`; do
	CONF_HEIGHT_NEW=`echo $i | cut -d ">" -f 2 | cut -d "<" -f 1`
	if [ ${CONF_HEIGHT_NEW} -gt ${CONF_HEIGHT} ]; then
		CONF_HEIGHT=${CONF_HEIGHT_NEW}
	fi
done

CONF_WIDTH=0
for i in `cat ~/.config/monitors.xml  | grep width`; do
	CONF_WIDTH_NEW=`echo $i | cut -d ">" -f 2 | cut -d "<" -f 1`
	if [ ${CONF_WIDTH_NEW} -gt ${CONF_WIDTH} ]; then
		CONF_WIDTH=${CONF_WIDTH_NEW}
	fi
done

RDP_WIDTH=`expr ${CONF_WIDTH} - 4`
RDP_HEIGHT=`expr ${CONF_HEIGHT} - 80`

/usr/bin/rdesktop -K -g ${RDP_WIDTH}x${RDP_HEIGHT} ${RDP_SERVER}
