#!/bin/bash

if [ $# -ne 1 ]; then
	echo "Usage `basename $0` host_list_file";
	exit 1;
fi

HOST_LIST_FILE=$1;

if [ ! -f ${HOST_LIST_FILE} ]; then
	echo "ERROR: ${HOST_LIST_FILE} is not a regular file.";
	exit 1;
fi

for i in `cat ${HOST_LIST_FILE}`; do
	ssh-keygen -f "${HOME}/.ssh/known_hosts" -R ${i};
done
