#!/bin/bash

SSH_HOST_NAME=${1};
SSH_KNOWN_HOSTS_FILE=${HOME}/.ssh/known_hosts;

if [ -z "${SSH_HOST_NAME}" ]; then
	echo -e "Usage: `basename ${0}` FQDN\n";
	exit 1;
fi

if [ ! -f ${SSH_KNOWN_HOSTS_FILE} ]; then
	echo "ERROR: ${SSH_KNOWN_HOSTS_FILE} not found."
	exit 1;
fi

ssh-keygen -R ${SSH_HOST_NAME} -f "${SSH_KNOWN_HOSTS_FILE}";

SSH_HOST_IP=`nslookup ${SSH_HOST_NAME} | grep ^Address: | grep -v "#" | awk '{print $2}' | grep -v "^127"`;

if [ -n "${SSH_HOST_IP}" ]; then
	ssh-keygen -R ${SSH_HOST_IP} -f "${SSH_KNOWN_HOSTS_FILE}";
fi

exit 0
