#!/bin/bash

# This script resets the know host entries from my known_hosts file
# it's mainly used because I rebuild test VMs and had to remove the
# keys manually every time.

HOST_LIST_FILE="${1}";
if [ -z "${HOST_LIST_FILE}" ]; then
	echo "Usage `basename ${0}` <host_list_file>";
	exit 1;
fi

if [ ! -f ${HOST_LIST_FILE} ]; then
	echo "No such file: ${HOST_LIST_FILE}.";
	exit 1;
fi

for i in `cat ${HOST_LIST_FILE}`; do
	echo ${i};
	ssh-keygen -f ~/.ssh/known_hosts -R ${i};
done;

exit 0;
