#!/usr/bin/env bash

print_usage () {
  local PROGNAME="${1}"
  if [ -z "${PROGNAME}" ]; then
    echo "f:${FUNCNAME[0]} l:${LINENO} ERROR: No program name specified."
    return 1
  fi

  echo "Purpose of the script"
  echo ""
  echo "Usage: ${PROGNAME} <option> height"
  echo "    height: height of terminal"
  echo ""
  echo "  Options:"
  echo "    -h: Print out this message."

  return 0
}


main () {
  local PROGNAME
  PROGNAME=$(basename "$0")

  while getopts dh opts; do
    case ${opts} in
      h) print_usage "${PROGNAME}"
         exit 0
         ;;
      *) print_usage "${PROGNAME}"
         exit 0
         ;;
    esac
  done
  shift "$(( OPTIND - 1 ))"

  if [ $# -ne 1 ]; then
    echo "ERROR: Wrong number of arguments."
    print_usage "${PROGNAME}"
    exit 1
  fi

  local LT_HEIGHT=${1}
  local INITIAL_WINDOW=$(tmux display-message -p '#I')

  # Not a tmux session
  [ -z "${TMUX}" ] && exit 0

  # Single window session not resizing
  [ "$(tmux list-panes | wc -l)" -lt 2 ] && exit 0
    
  while true; do
    local CURRENT_WINDOW=$(tmux display-message -p '#I')
    if [ "${CURRENT_WINDOW}" -eq "${INITIAL_WINDOW}" ]; then
      tmux resize-pane  -y ${LT_HEIGHT}
    fi
    sleep 5
  done

  exit 0
}

main "$@"
